# Generated by Django 5.1.5 on 2025-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_date_post_date_posted_post_content_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='Express yourself'),
        ),
    ]
